/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface ComplianceInterface extends Interface {
    getFunction(nameOrSignature: "COMPLIANCE_OFFICER" | "DEFAULT_ADMIN_ROLE" | "allowlist" | "allowlisted" | "blockAddress" | "blocked" | "checkTransfer" | "dailyLimit" | "dailyUsage" | "getRoleAdmin" | "grantRole" | "hasRole" | "recordUsage" | "removeFromAllowlist" | "renounceRole" | "revokeRole" | "setDailyLimit" | "supportsInterface" | "unblockAddress"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AddressAllowlisted" | "AddressBlocked" | "AddressRemoved" | "AddressUnblocked" | "DailyLimitSet" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked"): EventFragment;

    encodeFunctionData(functionFragment: 'COMPLIANCE_OFFICER', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'allowlist', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'allowlisted', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'blockAddress', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'blocked', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'checkTransfer', values: [AddressLike, AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'dailyLimit', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'dailyUsage', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'recordUsage', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'removeFromAllowlist', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setDailyLimit', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'unblockAddress', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'COMPLIANCE_OFFICER', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allowlist', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allowlisted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'blockAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'blocked', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'checkTransfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'dailyLimit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'dailyUsage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordUsage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeFromAllowlist', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setDailyLimit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unblockAddress', data: BytesLike): Result;
  }

  
    export namespace AddressAllowlistedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AddressBlockedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AddressRemovedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AddressUnblockedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DailyLimitSetEvent {
      export type InputTuple = [tokenId: BigNumberish, limit: BigNumberish];
      export type OutputTuple = [tokenId: bigint, limit: bigint];
      export interface OutputObject {tokenId: bigint, limit: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Compliance extends BaseContract {
    
    connect(runner?: ContractRunner | null): Compliance;
    waitForDeployment(): Promise<this>;

    interface: ComplianceInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    COMPLIANCE_OFFICER: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    allowlist: TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    allowlisted: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    blockAddress: TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    blocked: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    checkTransfer: TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, amount: BigNumberish, ],
      [[boolean, string] & {compliant: boolean, reason: string }],
      'view'
    >
    

    
    dailyLimit: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    dailyUsage: TypedContractMethod<
      [arg0: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    recordUsage: TypedContractMethod<
      [tokenId: BigNumberish, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    removeFromAllowlist: TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setDailyLimit: TypedContractMethod<
      [tokenId: BigNumberish, limit: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    unblockAddress: TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'COMPLIANCE_OFFICER'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'allowlist'): TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'allowlisted'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'blockAddress'): TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'blocked'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'checkTransfer'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, amount: BigNumberish, ],
      [[boolean, string] & {compliant: boolean, reason: string }],
      'view'
    >;
getFunction(nameOrSignature: 'dailyLimit'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'dailyUsage'): TypedContractMethod<
      [arg0: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'recordUsage'): TypedContractMethod<
      [tokenId: BigNumberish, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'removeFromAllowlist'): TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setDailyLimit'): TypedContractMethod<
      [tokenId: BigNumberish, limit: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'unblockAddress'): TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AddressAllowlisted'): TypedContractEvent<AddressAllowlistedEvent.InputTuple, AddressAllowlistedEvent.OutputTuple, AddressAllowlistedEvent.OutputObject>;
getEvent(key: 'AddressBlocked'): TypedContractEvent<AddressBlockedEvent.InputTuple, AddressBlockedEvent.OutputTuple, AddressBlockedEvent.OutputObject>;
getEvent(key: 'AddressRemoved'): TypedContractEvent<AddressRemovedEvent.InputTuple, AddressRemovedEvent.OutputTuple, AddressRemovedEvent.OutputObject>;
getEvent(key: 'AddressUnblocked'): TypedContractEvent<AddressUnblockedEvent.InputTuple, AddressUnblockedEvent.OutputTuple, AddressUnblockedEvent.OutputObject>;
getEvent(key: 'DailyLimitSet'): TypedContractEvent<DailyLimitSetEvent.InputTuple, DailyLimitSetEvent.OutputTuple, DailyLimitSetEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;

    filters: {
      
      'AddressAllowlisted(address)': TypedContractEvent<AddressAllowlistedEvent.InputTuple, AddressAllowlistedEvent.OutputTuple, AddressAllowlistedEvent.OutputObject>;
      AddressAllowlisted: TypedContractEvent<AddressAllowlistedEvent.InputTuple, AddressAllowlistedEvent.OutputTuple, AddressAllowlistedEvent.OutputObject>;
    

      'AddressBlocked(address)': TypedContractEvent<AddressBlockedEvent.InputTuple, AddressBlockedEvent.OutputTuple, AddressBlockedEvent.OutputObject>;
      AddressBlocked: TypedContractEvent<AddressBlockedEvent.InputTuple, AddressBlockedEvent.OutputTuple, AddressBlockedEvent.OutputObject>;
    

      'AddressRemoved(address)': TypedContractEvent<AddressRemovedEvent.InputTuple, AddressRemovedEvent.OutputTuple, AddressRemovedEvent.OutputObject>;
      AddressRemoved: TypedContractEvent<AddressRemovedEvent.InputTuple, AddressRemovedEvent.OutputTuple, AddressRemovedEvent.OutputObject>;
    

      'AddressUnblocked(address)': TypedContractEvent<AddressUnblockedEvent.InputTuple, AddressUnblockedEvent.OutputTuple, AddressUnblockedEvent.OutputObject>;
      AddressUnblocked: TypedContractEvent<AddressUnblockedEvent.InputTuple, AddressUnblockedEvent.OutputTuple, AddressUnblockedEvent.OutputObject>;
    

      'DailyLimitSet(uint256,uint256)': TypedContractEvent<DailyLimitSetEvent.InputTuple, DailyLimitSetEvent.OutputTuple, DailyLimitSetEvent.OutputObject>;
      DailyLimitSet: TypedContractEvent<DailyLimitSetEvent.InputTuple, DailyLimitSetEvent.OutputTuple, DailyLimitSetEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    
    };
  }