/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface SettlementInterface extends Interface {
    getFunction(nameOrSignature: "APPROVER_ROLE" | "DEFAULT_ADMIN_ROLE" | "approveDeal" | "cancelDeal" | "createDeal" | "dealCount" | "deals" | "fundDeal" | "getRoleAdmin" | "grantRole" | "hasApproved" | "hasRole" | "onERC1155BatchReceived" | "onERC1155Received" | "renounceRole" | "revokeRole" | "settleDeal" | "supportsInterface"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DealApproved" | "DealCancelled" | "DealCreated" | "DealFunded" | "DealSettled" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked"): EventFragment;

    encodeFunctionData(functionFragment: 'APPROVER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'approveDeal', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelDeal', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createDeal', values: [AddressLike, AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'dealCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'deals', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'fundDeal', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasApproved', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'onERC1155BatchReceived', values: [AddressLike, AddressLike, BigNumberish[], BigNumberish[], BytesLike]): string;
encodeFunctionData(functionFragment: 'onERC1155Received', values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'settleDeal', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'APPROVER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approveDeal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelDeal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createDeal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'dealCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fundDeal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasApproved', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'onERC1155BatchReceived', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'onERC1155Received', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'settleDeal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
  }

  
    export namespace DealApprovedEvent {
      export type InputTuple = [dealId: BigNumberish, approver: AddressLike];
      export type OutputTuple = [dealId: bigint, approver: string];
      export interface OutputObject {dealId: bigint, approver: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DealCancelledEvent {
      export type InputTuple = [dealId: BigNumberish];
      export type OutputTuple = [dealId: bigint];
      export interface OutputObject {dealId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DealCreatedEvent {
      export type InputTuple = [dealId: BigNumberish, seller: AddressLike, buyer: AddressLike];
      export type OutputTuple = [dealId: bigint, seller: string, buyer: string];
      export interface OutputObject {dealId: bigint, seller: string, buyer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DealFundedEvent {
      export type InputTuple = [dealId: BigNumberish];
      export type OutputTuple = [dealId: bigint];
      export interface OutputObject {dealId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DealSettledEvent {
      export type InputTuple = [dealId: BigNumberish];
      export type OutputTuple = [dealId: bigint];
      export interface OutputObject {dealId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Settlement extends BaseContract {
    
    connect(runner?: ContractRunner | null): Settlement;
    waitForDeployment(): Promise<this>;

    interface: SettlementInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    APPROVER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    approveDeal: TypedContractMethod<
      [dealId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    cancelDeal: TypedContractMethod<
      [dealId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createDeal: TypedContractMethod<
      [seller: AddressLike, buyer: AddressLike, tokenContract: AddressLike, tokenId: BigNumberish, amount: BigNumberish, approvalsRequired: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    dealCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    deals: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string, bigint, bigint, bigint, bigint, bigint] & {seller: string, buyer: string, tokenContract: string, tokenId: bigint, amount: bigint, approvalsRequired: bigint, approvalsReceived: bigint, status: bigint }],
      'view'
    >
    

    
    fundDeal: TypedContractMethod<
      [dealId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasApproved: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    onERC1155BatchReceived: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish[], arg3: BigNumberish[], arg4: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    onERC1155Received: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BigNumberish, arg4: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    settleDeal: TypedContractMethod<
      [dealId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'APPROVER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'approveDeal'): TypedContractMethod<
      [dealId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cancelDeal'): TypedContractMethod<
      [dealId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createDeal'): TypedContractMethod<
      [seller: AddressLike, buyer: AddressLike, tokenContract: AddressLike, tokenId: BigNumberish, amount: BigNumberish, approvalsRequired: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'dealCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'deals'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string, bigint, bigint, bigint, bigint, bigint] & {seller: string, buyer: string, tokenContract: string, tokenId: bigint, amount: bigint, approvalsRequired: bigint, approvalsReceived: bigint, status: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'fundDeal'): TypedContractMethod<
      [dealId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasApproved'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'onERC1155BatchReceived'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish[], arg3: BigNumberish[], arg4: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'onERC1155Received'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BigNumberish, arg4: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'settleDeal'): TypedContractMethod<
      [dealId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;

    getEvent(key: 'DealApproved'): TypedContractEvent<DealApprovedEvent.InputTuple, DealApprovedEvent.OutputTuple, DealApprovedEvent.OutputObject>;
getEvent(key: 'DealCancelled'): TypedContractEvent<DealCancelledEvent.InputTuple, DealCancelledEvent.OutputTuple, DealCancelledEvent.OutputObject>;
getEvent(key: 'DealCreated'): TypedContractEvent<DealCreatedEvent.InputTuple, DealCreatedEvent.OutputTuple, DealCreatedEvent.OutputObject>;
getEvent(key: 'DealFunded'): TypedContractEvent<DealFundedEvent.InputTuple, DealFundedEvent.OutputTuple, DealFundedEvent.OutputObject>;
getEvent(key: 'DealSettled'): TypedContractEvent<DealSettledEvent.InputTuple, DealSettledEvent.OutputTuple, DealSettledEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;

    filters: {
      
      'DealApproved(uint256,address)': TypedContractEvent<DealApprovedEvent.InputTuple, DealApprovedEvent.OutputTuple, DealApprovedEvent.OutputObject>;
      DealApproved: TypedContractEvent<DealApprovedEvent.InputTuple, DealApprovedEvent.OutputTuple, DealApprovedEvent.OutputObject>;
    

      'DealCancelled(uint256)': TypedContractEvent<DealCancelledEvent.InputTuple, DealCancelledEvent.OutputTuple, DealCancelledEvent.OutputObject>;
      DealCancelled: TypedContractEvent<DealCancelledEvent.InputTuple, DealCancelledEvent.OutputTuple, DealCancelledEvent.OutputObject>;
    

      'DealCreated(uint256,address,address)': TypedContractEvent<DealCreatedEvent.InputTuple, DealCreatedEvent.OutputTuple, DealCreatedEvent.OutputObject>;
      DealCreated: TypedContractEvent<DealCreatedEvent.InputTuple, DealCreatedEvent.OutputTuple, DealCreatedEvent.OutputObject>;
    

      'DealFunded(uint256)': TypedContractEvent<DealFundedEvent.InputTuple, DealFundedEvent.OutputTuple, DealFundedEvent.OutputObject>;
      DealFunded: TypedContractEvent<DealFundedEvent.InputTuple, DealFundedEvent.OutputTuple, DealFundedEvent.OutputObject>;
    

      'DealSettled(uint256)': TypedContractEvent<DealSettledEvent.InputTuple, DealSettledEvent.OutputTuple, DealSettledEvent.OutputObject>;
      DealSettled: TypedContractEvent<DealSettledEvent.InputTuple, DealSettledEvent.OutputTuple, DealSettledEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    
    };
  }